### ISSUE TITLE
in compile it cannot show run time error.It show wrong ans.

### ISSUE THREAD

**Issue by bondhansarker** [shawon100/RUET-OJ#2]

**Comment by shawon100** [comment]
Please attach the code and test cases.

**Comment by bondhansarker** [comment]
Just print 5/0

**Comment by shawon100** [comment]
yeah. in php 7.2, it is run time error. i have checked just now. what is your php version?

**Comment by bondhansarker** [comment]
I dont know ! May be the default one ! But I got this in the website. I
didnot understand bro ! I tried this in python ! I face difficulty in this
thing ! Windows  give a error sending notification while it is runtime
error !

**Comment by shawon100** [comment]
Windows??? It is for linux based os not for windows. Please read the readme of this repo carefully

**Comment by bondhansarker** [comment]
Brother I told about my project problem ! I fall in this problem for
working with windows !

**Comment by bondhansarker** [comment]
![image](https://user-images.githubusercontent.com/47887595/67789181-baa9a400-fa9d-11e9-8103-57a72ba1e21a.png)
![image](https://user-images.githubusercontent.com/47887595/67789211-cb5a1a00-fa9d-11e9-8e5e-eb6962b18763.png)

**Comment by shawon100** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/47887595/67789181-baa9a400-fa9d-11e9-8103-57a72ba1e21a.png)
> ![image](https://user-images.githubusercontent.com/47887595/67789211-cb5a1a00-fa9d-11e9-8e5e-eb6962b18763.png)

This problem is happening for online server openshift's compiler problem. Try on your offline linux server
